trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: '1.14.3'
  DEV_ENVIRONMENT: dev

stages:
# =========================
# Stage 1 - Terraform Validate
# =========================
- stage: TerraformValidate
  jobs:
  - job: Validate
    steps:

    - task: AzureCLI@2
      displayName: Terraform Init + Validate
      inputs:
        azureSubscription: terraform-aks-azurerm-svc-con
        scriptType: bash
        addSpnToEnvironment: true
        scriptLocation: inlineScript
        inlineScript: |
          set -e

          echo "Installing Terraform..."
          curl -fsSL https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -o terraform.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/

          cd terraform-manifests

          export ARM_USE_OIDC=true

          terraform version

          terraform init \
            -backend-config="resource_group_name=terraform-storage-rg" \
            -backend-config="storage_account_name=hichemsa" \
            -backend-config="container_name=tfstatefiles" \
            -backend-config="key=aks-base.tfstate"

          terraform validate

    - task: PublishPipelineArtifact@1
      displayName: Publish Terraform Manifests
      inputs:
        targetPath: terraform-manifests
        artifact: terraform-manifests

# =========================
# Stage 2 - Deploy DEV
# =========================
- stage: DeployDEV
  dependsOn: TerraformValidate
  jobs:
  - deployment: DeployDevAKS
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: terraform-manifests
              path: terraform-manifests

          - task: DownloadSecureFile@1
            name: sshkey
            inputs:
              secureFile: aks-terraform-devops-ssh-key-ububtu.pub

          - task: AzureCLI@2
            displayName: Terraform Plan + Apply (DEV)
            inputs:
              azureSubscription: terraform-aks-azurerm-svc-con
              scriptType: bash
              addSpnToEnvironment: true
              scriptLocation: inlineScript
              inlineScript: |
                set -e

                echo "Installing Terraform..."
                curl -fsSL https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -o terraform.zip
                unzip -o terraform.zip
                sudo mv -f terraform /usr/local/bin/terraform
                sudo chmod +x /usr/local/bin/terraform

                terraform version

                export ARM_USE_OIDC=true

                cd terraform-manifests

                terraform init -reconfigure\
                  -backend-config="resource_group_name=terraform-storage-rg" \
                  -backend-config="storage_account_name=hichemsa" \
                  -backend-config="container_name=tfstatefiles" \
                  -backend-config="key=aks-${DEV_ENVIRONMENT}.tfstate"

                terraform plan \
                  -var ssh_public_key=$(sshkey.secureFilePath) \
                  -var environment=${DEV_ENVIRONMENT} \
                  -out=tfplan.out

                terraform apply -auto-approve tfplan.out
